### PR TITLE
Namespace GoSquared classes and corrected Trend API

### PR DESCRIPTION
**Pull request by Sylvain**
Hi! 

I made some improvement in the gem:
- The classes were not namespaced so they were interfering with other classes defined in my Rails application. By putting them on the GoSquared namespace, we are sure to avoid naming collision.
- The Trend class was not implemented as described in the documentation (and therefore not working) for the dateFormat (it was date_format) and sourceType was not present

Let me know if you need any information.

Sylvain

### CODE REVIEW

**Comment by russellvaughan** [comment]
Thanks very much for this Sylvian. I will have a look through ASAP. much appreciated.

**Comment by russellvaughan** [comment]
Hey Sylvian, 

Have had a look through this and some great additions. The namespacing is a great spot and will incorporate that.  

The date_format correction is also a great spot in the docs. The docs are auto generated and in that instance defaulted to camelCase,  I feel it would be better to stick to Ruby convention in the library and stick with snake_case for both ```date_format``` and ```source_type```. So i've opted to amend the docs instead of the library in that case.

**Comment by Sylvain** [comment]
@russellvaughan OK no problem. In any case source_type was missing and I needed it. But no pb to use snake_case which is, indeed, more ruby-style.

**Comment by Sylvain** [comment]
👍

**Pull request merged**
